/-
Copyright (c) 2026 Daniel Fagerström. All rights reserved.
Released under the Apache 2.0 license as described in the file LICENSES/Apache-2.0.txt.
Authors: Daniel Fagerström
-/
import SpatialLine
/-!
# The trust-boundary guard (release export)

`lake env lean CIAxiomGuard.lean` prints the axiom usage of every named declaration of this
export. Every axiom that appears must be one of Lean's three logical axioms or a name declared
in `blueprint/trust-boundary.txt` (the eleven interface names of the full development; this
paper's theorems rest on four of them). The list is the development repository's guard
restricted to the exported declarations; see README.md.
-/

#print axioms SpatialLine.CascadeFamily
#print axioms SpatialLine.IsScaleCovariant
#print axioms SpatialLine.IsPositiveDefinite
#print axioms SpatialLine.IsSymNegDef
#print axioms SpatialLine.IsSelfDecomposable
#print axioms SpatialLine.SymLevyPair.exponent
#print axioms SpatialLine.SDProfile.exponent
#print axioms SpatialLine.fourierCos
#print axioms SpatialLine.reflL1
#print axioms SpatialLine.cin
#print axioms SpatialLine.HasProfileTail
#print axioms SpatialLine.cinSuperpositionL
#print axioms SpatialLine.symbol
#print axioms SpatialLine.besselK
#print axioms SpatialLine.IsCompletelyMonotone
#print axioms SpatialLine.signChangesAE
#print axioms SpatialLine.IsVariationDiminishing
#print axioms SpatialLine.IsPolyaExponent
#print axioms SpatialLine.integrable_cos_mul
#print axioms SpatialLine.integrable_sin_mul
#print axioms SpatialLine.fourierCos_dirac_zero
#print axioms SpatialLine.fourierCos_eq_charFun_re
#print axioms SpatialLine.charFun_eq_fourierCos_of_symmetric
#print axioms SpatialLine.fourier_uniqueness
#print axioms SpatialLine.levy_continuity
#print axioms SpatialLine.SymLevyPair.quadratic_growth
#print axioms SpatialLine.SymLevyPair.quadratic_growth_isBigO
#print axioms SpatialLine.SymLevyPair.exponentL_ne_top
#print axioms SpatialLine.profile_integrability
#print axioms SpatialLine.lintegral_ofReal_ne_top_of_integrableOn
#print axioms SpatialLine.sFinite_profileMeasure
#print axioms SpatialLine.profile_integrability_pair
#print axioms SpatialLine.profile_integrability_mem
#print axioms SpatialLine.laplace_uniqueness_locally_finite
#print axioms SpatialLine.charFun_eq_one_iff
#print axioms SpatialLine.lattice_zero_isClosedSubgroup
#print axioms SpatialLine.lattice_zero_trichotomy
#print axioms SpatialLine.lattice_zero_eq_univ_iff
#print axioms SpatialLine.lattice_zero_mem_iff
#print axioms SpatialLine.lattice_zero_exponent
#print axioms SpatialLine.lattice_zero_example_mem
#print axioms SpatialLine.lattice_zero_example_lattice
#print axioms SpatialLine.two_members_gaussian
#print axioms SpatialLine.two_members_matern
#print axioms SpatialLine.gaussianCascadeFamily
#print axioms SpatialLine.MaternData.cascadeFamily
#print axioms SpatialLine.eq_dirac_of_mconvL1_eq_id
#print axioms SpatialLine.norm_mconvL1_sub_le
#print axioms SpatialLine.tendsto_norm_mconvL1_sub_of_tendsto_charFun
#print axioms SpatialLine.integral_eq_zero_of_odd
#print axioms SpatialLine.integral_smul_exp_eq
#print axioms SpatialLine.ae_eq_zero_of_even_of_integral_cos_eq_zero
#print axioms SpatialLine.one_sub_sinc_le_sq
#print axioms SpatialLine.intervalIntegral_one_sub_cos
#print axioms SpatialLine.tendsto_sinc_natCast_mul
#print axioms SpatialLine.SymLevyPair.exponent_eq
#print axioms SpatialLine.SymLevyPair.intervalIntegral_exponent
#print axioms SpatialLine.SymLevyPair.tendsto_sincDefect_div_sq
#print axioms SpatialLine.SymLevyPair.eq_zero_of_tendsto_sincDefect
#print axioms SpatialLine.no_positivity_example
#print axioms SpatialLine.charFun_add_measure
#print axioms SpatialLine.charFun_withDensity_toNNReal
#print axioms SpatialLine.withDensity_pos_eq_of_fourierCos_eq
#print axioms SpatialLine.ae_nonneg_of_fourierCos_eq
#print axioms SpatialLine.integral_withDensity_ofReal
#print axioms SpatialLine.integral_withDensity_ofReal_of_nonneg
#print axioms SpatialLine.isNonneg_iff_zero_le
#print axioms SpatialLine.ae_nonneg_of_isNonneg_bconv
#print axioms SpatialLine.ae_nonneg_kernel_of_isPositive
#print axioms SpatialLine.no_positivity_admissible_of_positive
#print axioms SpatialLine.no_positivity_positive_of_admissible
#print axioms SpatialLine.no_positivity_classification
#print axioms SpatialLine.representation_existsUnique
#print axioms SpatialLine.representation_symmetric
#print axioms SpatialLine.representation_converse
#print axioms SpatialLine.nonvanishing
#print axioms SpatialLine.nonvanishing_exponent
#print axioms SpatialLine.dilation_invariance
#print axioms SpatialLine.dilation_atom
#print axioms SpatialLine.additivity
#print axioms SpatialLine.smoothed_transmittance
#print axioms SpatialLine.smoothed_transmittance_strictAnti
#print axioms SpatialLine.covariance_fourier
#print axioms SpatialLine.covariance_similarity
#print axioms SpatialLine.action_rigidity_injective
#print axioms SpatialLine.action_rigidity_group
#print axioms SpatialLine.action_rigidity_continuous
#print axioms SpatialLine.action_rigidity_no_fixed_point
#print axioms SpatialLine.monotonicity_zero_set
#print axioms SpatialLine.monotonicity_strict
#print axioms SpatialLine.no_lattice
#print axioms SpatialLine.canonical_gauge_orbit
#print axioms SpatialLine.canonical_gauge_of_levy
#print axioms SpatialLine.sub_one_sub_exp_neg_le
#print axioms SpatialLine.one_sub_sinc_ge
#print axioms SpatialLine.exists_limit_measure
#print axioms SpatialLine.increments_levy
#print axioms SpatialLine.canonical_gauge
#print axioms SpatialLine.convPow
#print axioms SpatialLine.isSymmetric_convPow
#print axioms SpatialLine.fourierCos_convPow
#print axioms SpatialLine.increments_levy_infinitely_divisible
#print axioms SpatialLine.increments_levy_id_measure
#print axioms SpatialLine.SDProfile.exponentL_ne_top
#print axioms SpatialLine.admissible_cone
#print axioms SpatialLine.sd_exponents_three_implies_one
#print axioms SpatialLine.sd_increment_pair
#print axioms SpatialLine.setLIntegral_Ioi_comp_mul
#print axioms SpatialLine.sd_dilate_pair
#print axioms SpatialLine.sd_increment_isSymLevyExponent
#print axioms SpatialLine.CascadeData.cascadeCore
#print axioms SpatialLine.CascadeData.continuousOn_mconvL1
#print axioms SpatialLine.ConstructionData.chi_continuousOn
#print axioms SpatialLine.exists_isSymmetric_of_isSymLevyExponent
#print axioms SpatialLine.main_construction
#print axioms SpatialLine.strict_positivity_monotone
#print axioms SpatialLine.gaussianDatum
#print axioms SpatialLine.gaussianDatum_exponent
#print axioms SpatialLine.semigroup_case_gaussian
#print axioms SpatialLine.lintegral_intervalIntegral_of_hasProfileTail
#print axioms SpatialLine.lintegral_min_one_sq_ne_top
#print axioms SpatialLine.lintegral_log_max_one_ne_top
#print axioms SpatialLine.measure_Ioi_ne_top
#print axioms SpatialLine.tendsto_measure_Ioi_nhdsGT
#print axioms SpatialLine.sd_exponents_profile_measure
#print axioms SpatialLine.hasDerivAt_cin
#print axioms SpatialLine.integrable_cin_dilate
#print axioms SpatialLine.exponent_eq_integral_cin
#print axioms SpatialLine.hasDerivAt_exponent
#print axioms SpatialLine.mul_deriv_exponent
#print axioms SpatialLine.symbolL_eq_ofReal
#print axioms SpatialLine.sd_exponents_symbol
#print axioms SpatialLine.sd_exponents_three_implies_two
#print axioms SpatialLine.symLevyPair_dilate
#print axioms SpatialLine.symLevyPair_add
#print axioms SpatialLine.dilate_le_of_increments
#print axioms SpatialLine.tonelli_window
#print axioms SpatialLine.setLIntegral_dyadicDensity
#print axioms SpatialLine.exists_antitone_density
#print axioms SpatialLine.SymLevyPair.measure_Ioi_ne_top
#print axioms SpatialLine.map_log_shift
#print axioms SpatialLine.map_exp_withDensity
#print axioms SpatialLine.dyadicDensity_ne_top
#print axioms SpatialLine.exists_profile_of_dilate_le
#print axioms SpatialLine.SDProfile.exponentL_neg
#print axioms SpatialLine.SDProfile.exponent_neg
#print axioms SpatialLine.sd_exponents_one_implies_three
#print axioms SpatialLine.SymLevyPair.continuous_exponent
#print axioms SpatialLine.SDProfile.continuous_exponent
#print axioms SpatialLine.main_uniqueness
#print axioms SpatialLine.fourierCos_eq_exp_neg_exponent
#print axioms SpatialLine.isSymLevyExponent_dilate_diff
#print axioms SpatialLine.exists_kernelFamily
#print axioms SpatialLine.main_analysis_of_profileForm
#print axioms SpatialLine.main_analysis
#print axioms SpatialLine.main_analysis_exists
#print axioms SpatialLine.main_characterization
#print axioms SpatialLine.ae_restrict_Ioi_mul_iff
#print axioms SpatialLine.strict_positivity_strict
#print axioms SpatialLine.strict_positivity_consequences
#print axioms SpatialLine.isSelfDecomposable_kernel
#print axioms SpatialLine.kernel_ne_dirac_zero
#print axioms SpatialLine.kernel_regularity
#print axioms SpatialLine.integrableOn_stableIntegrand
#print axioms SpatialLine.stableConst_pos
#print axioms SpatialLine.stableDatum
#print axioms SpatialLine.stableDatum_exponent
#print axioms SpatialLine.semigroup_case_profile
#print axioms SpatialLine.eq_mul_of_addOn_of_continuousOn
#print axioms SpatialLine.exists_eq_rpow_of_mul
#print axioms SpatialLine.semigroup_case
#print axioms SpatialLine.SymLevyPair.exponent_zero
#print axioms SpatialLine.SymLevyPair.exponent_neg
#print axioms SpatialLine.log_max_one_le_cin
#print axioms SpatialLine.lintegral_log_max_one_ne_top_of_cin
#print axioms SpatialLine.lintegral_deriv_Ioc_le
#print axioms SpatialLine.lintegral_swap_cin
#print axioms SpatialLine.eq_zero_of_hasDerivAt_zero_of_continuous
#print axioms SpatialLine.sd_exponents_two_implies_three
#print axioms SpatialLine.cin_elementary
#print axioms SpatialLine.cin_expansion_zero
#print axioms SpatialLine.cin_expansion_top
#print axioms SpatialLine.cin_ray
#print axioms SpatialLine.cin_superposition
#print axioms SpatialLine.cin_superposition_exists
#print axioms SpatialLine.cin_origin_singularity_cin_ray
#print axioms SpatialLine.cinSDProfile
#print axioms SpatialLine.choquetSDProfile
#print axioms SpatialLine.exists_tailMeasure
#print axioms SpatialLine.integral_sin_mul_exp_neg_Ioi
#print axioms SpatialLine.integral_frullani
#print axioms SpatialLine.maternDatum
#print axioms SpatialLine.maternDatum_exponent
#print axioms SpatialLine.matern_exponent
#print axioms SpatialLine.matern_transforms
#print axioms SpatialLine.matern_gauge
#print axioms SpatialLine.matern_gauge_profile
#print axioms SpatialLine.matern_rational
#print axioms SpatialLine.matern_rational_polynomial
#print axioms SpatialLine.measurable_brownianLaw
#print axioms SpatialLine.isProbabilityMeasure_bind_brownianLaw
#print axioms SpatialLine.isSymmetric_bind_brownianLaw
#print axioms SpatialLine.fourierCos_bind_brownianLaw
#print axioms SpatialLine.lintegral_ofReal_ne_top_iff_integrableOn
#print axioms SpatialLine.one_sub_cos_mul_two_div
#print axioms SpatialLine.exponent_eq_add_integral
#print axioms SpatialLine.tendsto_exponent_div
#print axioms SpatialLine.tendsto_one_sub_exp_div
#print axioms SpatialLine.lintegral_sq_le_of_tendsto
#print axioms SpatialLine.moments_tails_variance
#print axioms SpatialLine.maternTransform_zero
#print axioms SpatialLine.integral_id_mul_maternProfile
#print axioms SpatialLine.matern_mean_variance
#print axioms SpatialLine.two_members_matern_moments
#print axioms SpatialLine.lintegral_symmetrise_of_even
#print axioms SpatialLine.fourierCos_symmetrise
#print axioms SpatialLine.lintegral_pow_brownianLaw
#print axioms SpatialLine.lintegral_gammaMeasure_rpow_mul_exp
#print axioms SpatialLine.integral_exp_neg_maternDelay
#print axioms SpatialLine.fourierCos_maternDelay_bind
#print axioms SpatialLine.lintegral_pow_maternDelay_bind
#print axioms SpatialLine.matern_gamma_mixture
#print axioms SpatialLine.matern_moments
#print axioms SpatialLine.conv_absolutelyContinuous
#print axioms SpatialLine.isSymmetric_conv
#print axioms SpatialLine.mconv_conv_bounded
#print axioms SpatialLine.signChangesAE_congr
#print axioms SpatialLine.measurable_mconv
#print axioms SpatialLine.mconv_bounded
#print axioms SpatialLine.exists_good_representative
#print axioms SpatialLine.isVariationDiminishing_conv
#print axioms SpatialLine.IsVariationDiminishingOrd
#print axioms SpatialLine.signChanges_mono
#print axioms SpatialLine.signChangesAE_le_of_ae
#print axioms SpatialLine.signChangesAE_le
#print axioms SpatialLine.exists_measurable_rep_signChanges_le
#print axioms SpatialLine.signChangesAE_eq_iInf_measurable
#print axioms SpatialLine.isVariationDiminishing_of_ord
